In [28]:
import os
import pandas as pd

In [29]:
folderPath = '/Users/bowenzhao/Desktop/UIUC/2026 Spring/IS 477/IS-477/csse_covid_19_daily_reports_us'
files = []
for f in os.listdir(folderPath):
    if '2021' in f:
        files.append(f)

df_list = []
for file in files:
    df_path = os.path.join(folderPath, file)
    df = pd.read_csv(df_path)
    df_list.append(df)

df_2021 = pd.concat(df_list, ignore_index=True)
display(df_2021)

,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,FIPS,...,Total_Test_Results,People_Hospitalized,Case_Fatality_Ratio,UID,ISO3,Testing_Rate,Hospitalization_Rate,Date,People_Tested,Mortality_Rate
0,Alabama,US,2021-07-05 04:31:17,32.3182,-86.9023,551298,11358,NaN,NaN,1.0,...,NaN,NaN,2.060229,84000001.0,USA,NaN,NaN,2021-07-04,NaN,NaN
1,Alaska,US,2021-07-05 04:31:17,61.3707,-152.4044,71384,377,NaN,NaN,2.0,...,2382952.0,NaN,0.528130,84000002.0,USA,325742.367182,NaN,2021-07-04,NaN,NaN
2,American Samoa,US,2021-07-05 04:31:17,-14.2710,-170.1320,0,0,NaN,NaN,60.0,...,2140.0,NaN,NaN,16.0,ASM,3846.084722,NaN,2021-07-04,NaN,NaN
3,Arizona,US,2021-07-05 04:31:17,33.7298,-111.4312,896960,17979,NaN,NaN,4.0,...,10294689.0,NaN,2.004437,84000004.0,USA,141435.489249,NaN,2021-07-04,NaN,NaN
4,Arkansas,US,2021-07-05 04:31:17,34.9697,-92.3731,350579,5913,NaN,NaN,5.0,...,3135625.0,NaN,1.686638,84000005.0,USA,103904.196561,NaN,2021-07-04,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21165,Virginia,US,2021-06-15 04:31:17,37.7693,-78.1700,677812,11318,NaN,NaN,51.0,...,7553224.0,NaN,1.669785,84000051.0,USA,88491.678128,NaN,2021-06-14,NaN,NaN
21166,Washington,US,2021-06-15 04:31:17,47.4009,-121.4905,444722,5782,NaN,NaN,53.0,...,7358062.0,NaN,1.300138,84000053.0,USA,96627.253988,NaN,2021-06-14,NaN,NaN
21167,West Virginia,US,2021-06-15 04:31:17,38.4912,-80.9545,163144,2853,NaN,NaN,54.0,...,2972502.0,NaN,1.748762,84000054.0,USA,165862.621760,NaN,2021-06-14,NaN,NaN
21168,Wisconsin,US,2021-06-15 04:31:17,44.2685,-89.6165,676276,8015,NaN,NaN,55.0,...,8893572.0,NaN,1.185167,84000055.0,USA,0.000015,NaN,2021-06-14,NaN,NaN
21169,Wyoming,US,2021-06-15 04:31:17,42.7560,-107.3025,61234,725,NaN,NaN,56.0,...,770872.0,NaN,1.183983,84000056.0,USA,133193.954651,NaN,2021-06-14,NaN,NaN

In [30]:
df_2021.columns

Index(['Province_State', 'Country_Region', 'Last_Update', 'Lat', 'Long_',
       'Confirmed', 'Deaths', 'Recovered', 'Active', 'FIPS', 'Incident_Rate',
       'Total_Test_Results', 'People_Hospitalized', 'Case_Fatality_Ratio',
       'UID', 'ISO3', 'Testing_Rate', 'Hospitalization_Rate', 'Date',
       'People_Tested', 'Mortality_Rate'],
      dtype='object')

In [31]:
df_2021.isna().sum()

Province_State              0
Country_Region              0
Last_Update                 0
Lat                       730
Long_                     730
Confirmed                   0
Deaths                      0
Recovered               18354
Active                  18354
FIPS                        0
Incident_Rate             730
Total_Test_Results       1112
People_Hospitalized     21170
Case_Fatality_Ratio       278
UID                         0
ISO3                        0
Testing_Rate             1112
Hospitalization_Rate    21170
Date                        0
People_Tested           21170
Mortality_Rate          21170
dtype: int64

In [32]:
len(df_2021['Date'].unique())

365

In [33]:
df_2021 = df_2021[['Date', 'Province_State', 'Confirmed', 'Deaths']].copy()
display(df_2021)

             Date  Province_State  Confirmed  Deaths
0      2021-07-04         Alabama     551298   11358
1      2021-07-04          Alaska      71384     377
2      2021-07-04  American Samoa          0       0
3      2021-07-04         Arizona     896960   17979
4      2021-07-04        Arkansas     350579    5913
...           ...             ...        ...     ...
21165  2021-06-14        Virginia     677812   11318
21166  2021-06-14      Washington     444722    5782
21167  2021-06-14   West Virginia     163144    2853
21168  2021-06-14       Wisconsin     676276    8015
21169  2021-06-14         Wyoming      61234     725

[21170 rows x 4 columns]

In [35]:
df_2021['Date'] = pd.to_datetime(df_2021['Date'])
df_2021 = df_2021.sort_values(['Province_State', 'Date'])

df_2021['New_Confirmed'] = df_2021.groupby('Province_State')['Confirmed'].diff()
df_2021['New_Deaths'] = df_2021.groupby('Province_State')['Deaths'].diff()

In [40]:
display(df_2021.sort_values(['Date', 'Province_State']))
df_2021_US = df_2021.groupby('Date')[['New_Confirmed', 'New_Deaths']].sum().reset_index()
display(df_2021_US)

            Date  Province_State  Confirmed  Deaths  New_Confirmed  New_Deaths
12992 2021-01-01         Alabama     365747    4872            NaN         NaN
12993 2021-01-01          Alaska      47019     206            NaN         NaN
12994 2021-01-01  American Samoa          0       0            NaN         NaN
12995 2021-01-01         Arizona     530267    9015            NaN         NaN
12996 2021-01-01        Arkansas     229442    3711            NaN         NaN
...          ...             ...        ...     ...            ...         ...
169   2021-12-31        Virginia    1118518   15587        17618.0        22.0
170   2021-12-31      Washington     849075    9853            0.0         0.0
171   2021-12-31   West Virginia     328162    5336            0.0         0.0
172   2021-12-31       Wisconsin    1120663   11173         8008.0        22.0
173   2021-12-31         Wyoming     115638    1526            0.0         0.0

[21170 rows x 6 columns]

          Date  New_Confirmed  New_Deaths
0   2021-01-01            0.0         0.0
1   2021-01-02       272624.0      2592.0
2   2021-01-03       203213.0      1401.0
3   2021-01-04       186732.0      2016.0
4   2021-01-05       232141.0      3576.0
..         ...            ...         ...
360 2021-12-27       506072.0      1846.0
361 2021-12-28       372461.0      2281.0
362 2021-12-29       511022.0      2355.0
363 2021-12-30       597951.0      1487.0
364 2021-12-31       512043.0       731.0

[365 rows x 3 columns]